development:
  adapter: postgresql
  database: tuesdayvotes_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: tuesdayvotes_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: tuesdayvotes_production
  pool: 5
  timeout: 5000